<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), global.json))\.props\DotNet.targets" />

  <ItemGroup>
    <PackageReference Include="FastEndpoints" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="Riok.Mapperly" />
    <PackageReference Include="NodaTime" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DepositStopLoss.Domain\DepositStopLoss.Domain.csproj" />
  </ItemGroup>

</Project>
