// <auto-generated />
using System;
using System.Collections.Generic;
using DepositStopLoss.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DepositStopLoss.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DepositStopLoss.Domain.Banking.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_banks_code");

                    b.ToTable("banks", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39364dee-7cb1-4273-8dfc-6efa5f5c1c53"),
                            Code = "TBC",
                            IsActive = true,
                            Name = "TBC Bank",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("afbb4296-a5f8-428f-a7c6-9edc9c7b5673"),
                            Code = "BOG",
                            IsActive = true,
                            Name = "Bank of Georgia",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("c73e6bfc-5efe-41d1-b80a-8cf425e75b3b"),
                            Code = "NBG",
                            IsActive = true,
                            Name = "National Bank of Georgia",
                            Type = 2
                        });
                });

            modelBuilder.Entity("DepositStopLoss.Domain.Banking.BankRateSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("api_url");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_id");

                    b.Property<int>("RateType")
                        .HasColumnType("integer")
                        .HasColumnName("rate_type");

                    b.HasKey("Id");

                    b.HasIndex("BankId", "RateType")
                        .IsUnique()
                        .HasDatabaseName("ix_bank_rate_sources_bank_rate_type");

                    b.ToTable("bank_rate_sources", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ccba9c58-034a-4b1d-8431-c74249969c0f"),
                            ApiUrl = "https://api.tbcbank.ge/v1/exchange-rates/commercial",
                            BankId = new Guid("39364dee-7cb1-4273-8dfc-6efa5f5c1c53"),
                            RateType = 1
                        },
                        new
                        {
                            Id = new Guid("6099cfd8-8a37-4b84-85b3-b0b880394cac"),
                            ApiUrl = "https://api.tbcbank.ge/v1/exchange-rates/concept",
                            BankId = new Guid("39364dee-7cb1-4273-8dfc-6efa5f5c1c53"),
                            RateType = 2
                        },
                        new
                        {
                            Id = new Guid("eaab9b5a-86e2-47dc-adad-9330cf6d9263"),
                            ApiUrl = "https://bankofgeorgia.ge/api/currencies",
                            BankId = new Guid("afbb4296-a5f8-428f-a7c6-9edc9c7b5673"),
                            RateType = 1
                        },
                        new
                        {
                            Id = new Guid("ba1a049a-7bb2-4213-835f-56b20aa13dfc"),
                            ApiUrl = "https://nbg.gov.ge/gw/api/ct/monetarypolicy/currencies/en/json",
                            BankId = new Guid("c73e6bfc-5efe-41d1-b80a-8cf425e75b3b"),
                            RateType = 1
                        });
                });

            modelBuilder.Entity("DepositStopLoss.Domain.Banking.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_id");

                    b.Property<decimal>("BuyRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("buy_rate");

                    b.Property<Instant>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<int>("FromCurrency")
                        .HasColumnType("integer")
                        .HasColumnName("from_currency");

                    b.Property<LocalDate>("RateDate")
                        .HasColumnType("date")
                        .HasColumnName("rate_date");

                    b.Property<int>("RateType")
                        .HasColumnType("integer")
                        .HasColumnName("rate_type");

                    b.Property<decimal>("SellRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("sell_rate");

                    b.Property<int>("ToCurrency")
                        .HasColumnType("integer")
                        .HasColumnName("to_currency");

                    b.HasKey("Id");

                    b.HasIndex("RateDate")
                        .HasDatabaseName("ix_exchange_rates_rate_date");

                    b.HasIndex("BankId", "FromCurrency", "ToCurrency", "RateDate", "RateType")
                        .IsUnique()
                        .HasDatabaseName("ix_exchange_rates_bank_currencies_date_type");

                    b.ToTable("exchange_rates", "public");
                });

            modelBuilder.Entity("DepositStopLoss.Domain.Banking.UserBankConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("access_token");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_id");

                    b.Property<Instant>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Instant?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("refresh_token");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<Instant>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "BankId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_bank_connections_user_bank");

                    b.ToTable("user_bank_connections", "public");
                });

            modelBuilder.Entity("DepositStopLoss.Domain.Deposits.Deposit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("annual_interest_rate");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_id");

                    b.Property<Instant?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<int>("Currency")
                        .HasColumnType("integer")
                        .HasColumnName("currency");

                    b.Property<Instant>("MaturityDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("maturity_date");

                    b.Property<Instant>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<int>("RateType")
                        .HasColumnType("integer")
                        .HasColumnName("rate_type");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("StopLossThreshold")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("stop_loss_threshold");

                    b.Property<int>("TermMonths")
                        .HasColumnType("integer")
                        .HasColumnName("term_months");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BankId")
                        .HasDatabaseName("ix_deposits_bank_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_deposits_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_deposits_user_id");

                    b.ToTable("deposits", "public");
                });

            modelBuilder.Entity("DepositStopLoss.Domain.Deposits.DepositContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Instant>("ContributedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contributed_at");

                    b.Property<Guid>("DepositId")
                        .HasColumnType("uuid")
                        .HasColumnName("deposit_id");

                    b.Property<decimal>("ExchangeRateAtContribution")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("exchange_rate");

                    b.HasKey("Id");

                    b.HasIndex("DepositId")
                        .HasDatabaseName("ix_deposit_contributions_deposit_id");

                    b.ToTable("deposit_contributions", "public");
                });

            modelBuilder.Entity("DepositStopLoss.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepositId")
                        .HasColumnType("uuid")
                        .HasColumnName("deposit_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<Instant?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Instant?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_notifications_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_notifications_user_status");

                    b.ToTable("notifications", "public");
                });

            modelBuilder.Entity("DepositStopLoss.Domain.Snapshots.DepositSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DepositId")
                        .HasColumnType("uuid")
                        .HasColumnName("deposit_id");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("exchange_rate");

                    b.Property<decimal>("ProfitLossPercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("profit_loss_percent");

                    b.Property<Instant>("SnapshotDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_date");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AccruedInterest", "DepositStopLoss.Domain.Snapshots.DepositSnapshot.AccruedInterest#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("accrued_interest");

                            b1.Property<int>("Currency")
                                .HasColumnType("integer")
                                .HasColumnName("accrued_interest_currency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalAmountInDepositCurrency", "DepositStopLoss.Domain.Snapshots.DepositSnapshot.TotalAmountInDepositCurrency#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_amount_deposit_currency");

                            b1.Property<int>("Currency")
                                .HasColumnType("integer")
                                .HasColumnName("total_amount_deposit_currency_code");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalAmountInUsd", "DepositStopLoss.Domain.Snapshots.DepositSnapshot.TotalAmountInUsd#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_amount_usd");

                            b1.Property<int>("Currency")
                                .HasColumnType("integer")
                                .HasColumnName("total_amount_usd_currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DepositId")
                        .HasDatabaseName("ix_deposit_snapshots_deposit_id");

                    b.HasIndex("DepositId", "SnapshotDate")
                        .HasDatabaseName("ix_deposit_snapshots_deposit_date");

                    b.ToTable("deposit_snapshots", "public");
                });

            modelBuilder.Entity("DepositStopLoss.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("EnableEmailNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_email_notifications");

                    b.Property<bool>("EnableTelegramNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_telegram_notifications");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<Instant?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<Instant>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("timezone");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_telegram_id");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("DepositStopLoss.Domain.Banking.BankRateSource", b =>
                {
                    b.HasOne("DepositStopLoss.Domain.Banking.Bank", null)
                        .WithMany("RateSources")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DepositStopLoss.Domain.Deposits.DepositContribution", b =>
                {
                    b.HasOne("DepositStopLoss.Domain.Deposits.Deposit", null)
                        .WithMany("Contributions")
                        .HasForeignKey("DepositId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DepositStopLoss.Domain.Banking.Bank", b =>
                {
                    b.Navigation("RateSources");
                });

            modelBuilder.Entity("DepositStopLoss.Domain.Deposits.Deposit", b =>
                {
                    b.Navigation("Contributions");
                });
#pragma warning restore 612, 618
        }
    }
}
